from django.urls import path
from .views import (
    fetch_exchange_rates,
    fetch_cad_exchange_rates,
    cad_to_php,
    cad_to_bdt,
    cad_to_brl,
    cad_to_usd,
    cad_to_xaf,
    cad_to_cop,
    cad_to_dop,
    cad_to_egp,
    cad_to_etb,
    cad_to_gtq,
    cad_to_gnf,
    cad_to_htg,
    cad_to_inr,
    cad_to_xof,
    cad_to_jmd,
    cad_to_kes,
    cad_to_mga,
    cad_to_mxn,
    cad_to_mad,
    cad_to_npr,
    cad_to_ngn,
    cad_to_pkr,
    cad_to_lkr,
    cad_to_tzs,
    cad_to_gmd,
    cad_to_tnd,
    cad_to_try,
    cad_to_ugx,
    cad_to_vnd,
    cad_to_zmw
)

urlpatterns = [
    path('currencyrates/', fetch_exchange_rates, name='currency-rates'),
    path('currencyrates/CAD/', fetch_cad_exchange_rates, name='fetch-cad-exchange-rates'),
    path('currencyrates/CAD/PHP', cad_to_php, name='cad-to-php'),
    path('currencyrates/CAD/BDT', cad_to_bdt, name='cad-to-bdt'),
    path('currencyrates/CAD/BRL', cad_to_brl, name='cad-to-brl'),
    path('currencyrates/CAD/USD', cad_to_usd, name='cad-to-usd'),
    path('currencyrates/CAD/XAF', cad_to_xaf, name='cad-to-xaf'),
    path('currencyrates/CAD/COP', cad_to_cop, name='cad-to-cop'),
    path('currencyrates/CAD/DOP', cad_to_dop, name='cad-to-dop'),
    path('currencyrates/CAD/EGP', cad_to_egp, name='cad-to-egp'),
    path('currencyrates/CAD/ETB', cad_to_etb, name='cad-to-etb'),
    path('currencyrates/CAD/GTQ', cad_to_gtq, name='cad-to-gtq'),
    path('currencyrates/CAD/GNF', cad_to_gnf, name='cad-to-gnf'),
    path('currencyrates/CAD/HTG', cad_to_htg, name='cad-to-htg'),
    path('currencyrates/CAD/INR', cad_to_inr, name='cad-to-inr'),
    path('currencyrates/CAD/XOF', cad_to_xof, name='cad-to-xof'),
    path('currencyrates/CAD/JMD', cad_to_jmd, name='cad-to-jmd'),
    path('currencyrates/CAD/KES', cad_to_kes, name='cad-to-kes'),
    path('currencyrates/CAD/MGA', cad_to_mga, name='cad-to-mga'),
    path('currencyrates/CAD/MXN', cad_to_mxn, name='cad-to-mxn'),
    path('currencyrates/CAD/MAD', cad_to_mad, name='cad-to-mad'),
    path('currencyrates/CAD/NPR', cad_to_npr, name='cad-to-npr'),
    path('currencyrates/CAD/NGN', cad_to_ngn, name='cad-to-ngn'),
    path('currencyrates/CAD/PKR', cad_to_pkr, name='cad-to-pkr'),
    path('currencyrates/CAD/LKR', cad_to_lkr, name='cad-to-lkr'),
    path('currencyrates/CAD/TZS', cad_to_tzs, name='cad-to-tzs'),
    path('currencyrates/CAD/GMD', cad_to_gmd, name='cad-to-gmd'),
    path('currencyrates/CAD/TND', cad_to_tnd, name='cad-to-tnd'),
    path('currencyrates/CAD/TRY', cad_to_try, name='cad-to-try'),
    path('currencyrates/CAD/UGX', cad_to_ugx, name='cad-to-ugx'),
    path('currencyrates/CAD/VND', cad_to_vnd, name='cad-to-vnd'),
    path('currencyrates/CAD/ZMW', cad_to_zmw, name='cad-to-zmw'),
]
