# Generated by Django 4.2.19 on 2025-02-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
